### ISSUE TITLE
Synced time in RedisDriver

### ISSUE THREAD

**Issue by pkruithof** [fieg/statistico#3]
It's a bit nit picking, but every microsecond counts when it comes to performance :wink: 

The syncedTime method in RedisDriver does a redundant addition/subtraction:

```php
protected function syncedTime()
{
    $now = time();
    list($redisTime) = $this->redis->time();

    $diff = $redisTime - $now;

    return $now + $diff;
}
```

This is the same:

```php
protected function syncedTime()
{
    return $this->redis->time()[0];
}
```

**Comment by fieg** [comment]
Fixed in 2a56c699c8bbe1e8ab04a63c697638396cf02531
